#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding					24
bspc config bottom_padding			0

bspc config split_ratio          0.52
bspc config gapless_monocle      false

bspc config ignore_ewmh_fullscreen off

bspc rule -a discord desktop='^6' follow=off focus=off
bspc rule -a polybar manage=off floating=on border=off
bspc rule -a pavucontrol state=floating

#AutoStart applications
picom --config $HOME/.config/picom/picom.conf &
dunst &
~/.fehbg &
$HOME/.config/polybar/launch.sh &
(sleep 3 && discord) &
