#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_fullscreen off

bspc rule -a discord desktop='^6' follow=on focus=off

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst &
$HOME/.config/polybar/launch.sh &
(sleep 3 && discord) &
