;
;
;         CCCCCCCCCCCCC                 lllllll                                                       
;      CCC::::::::::::C                 l:::::l                                                       
;    CC:::::::::::::::C                 l:::::l                                                       
;   C:::::CCCCCCCC::::C                 l:::::l                                                       
;  C:::::C       CCCCCC   ooooooooooo    l::::l    ooooooooooo   rrrrr   rrrrrrrrr       ssssssssss   
; C:::::C               oo:::::::::::oo  l::::l  oo:::::::::::oo r::::rrr:::::::::r    ss::::::::::s  
; C:::::C              o:::::::::::::::o l::::l o:::::::::::::::or:::::::::::::::::r ss:::::::::::::s 
; C:::::C              o:::::ooooo:::::o l::::l o:::::ooooo:::::orr::::::rrrrr::::::rs::::::ssss:::::s
; C:::::C              o::::o     o::::o l::::l o::::o     o::::o r:::::r     r:::::r s:::::s  ssssss 
; C:::::C              o::::o     o::::o l::::l o::::o     o::::o r:::::r     rrrrrrr   s::::::s      
; C:::::C              o::::o     o::::o l::::l o::::o     o::::o r:::::r                  s::::::s   
;  C:::::C       CCCCCCo::::o     o::::o l::::l o::::o     o::::o r:::::r            ssssss   s:::::s 
;   C:::::CCCCCCCC::::Co:::::ooooo:::::ol::::::lo:::::ooooo:::::o r:::::r            s:::::ssss::::::s
;    CC:::::::::::::::Co:::::::::::::::ol::::::lo:::::::::::::::o r:::::r            s::::::::::::::s 
;      CCC::::::::::::C oo:::::::::::oo l::::::l oo:::::::::::oo  r:::::r             s:::::::::::ss  
;         CCCCCCCCCCCCC   ooooooooooo   llllllll   ooooooooooo    rrrrrrr              sssssssssss    
;


[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #01827e
secondary = #8ABEB7
alert = #A54242
disabled = #707880
transparent = #00000000
