;
;
; PPPPPPPPPPPPPPPPP        OOOOOOOOO     LLLLLLLLLLL         YYYYYYY       YYYYYYYBBBBBBBBBBBBBBBBB               AAA               RRRRRRRRRRRRRRRRR   
; P::::::::::::::::P     OO:::::::::OO   L:::::::::L         Y:::::Y       Y:::::YB::::::::::::::::B             A:::A              R::::::::::::::::R  
; P::::::PPPPPP:::::P  OO:::::::::::::OO L:::::::::L         Y:::::Y       Y:::::YB::::::BBBBBB:::::B           A:::::A             R::::::RRRRRR:::::R 
; PP:::::P     P:::::PO:::::::OOO:::::::OLL:::::::LL         Y::::::Y     Y::::::YBB:::::B     B:::::B         A:::::::A            RR:::::R     R:::::R
;   P::::P     P:::::PO::::::O   O::::::O  L:::::L           YYY:::::Y   Y:::::YYY  B::::B     B:::::B        A:::::::::A             R::::R     R:::::R
;   P::::P     P:::::PO:::::O     O:::::O  L:::::L              Y:::::Y Y:::::Y     B::::B     B:::::B       A:::::A:::::A            R::::R     R:::::R
;   P::::PPPPPP:::::P O:::::O     O:::::O  L:::::L               Y:::::Y:::::Y      B::::BBBBBB:::::B       A:::::A A:::::A           R::::RRRRRR:::::R 
;   P:::::::::::::PP  O:::::O     O:::::O  L:::::L                Y:::::::::Y       B:::::::::::::BB       A:::::A   A:::::A          R:::::::::::::RR  
;   P::::PPPPPPPPP    O:::::O     O:::::O  L:::::L                 Y:::::::Y        B::::BBBBBB:::::B     A:::::A     A:::::A         R::::RRRRRR:::::R 
;   P::::P            O:::::O     O:::::O  L:::::L                  Y:::::Y         B::::B     B:::::B   A:::::AAAAAAAAA:::::A        R::::R     R:::::R
;   P::::P            O:::::O     O:::::O  L:::::L                  Y:::::Y         B::::B     B:::::B  A:::::::::::::::::::::A       R::::R     R:::::R
;   P::::P            O::::::O   O::::::O  L:::::L         LLLLLL   Y:::::Y         B::::B     B:::::B A:::::AAAAAAAAAAAAA:::::A      R::::R     R:::::R
; PP::::::PP          O:::::::OOO:::::::OLL:::::::LLLLLLLLL:::::L   Y:::::Y       BB:::::BBBBBB::::::BA:::::A             A:::::A   RR:::::R     R:::::R
; P::::::::P           OO:::::::::::::OO L::::::::::::::::::::::LYYYY:::::YYYY    B:::::::::::::::::BA:::::A               A:::::A  R::::::R     R:::::R
; P::::::::P             OO:::::::::OO   L::::::::::::::::::::::LY:::::::::::Y    B::::::::::::::::BA:::::A                 A:::::A R::::::R     R:::::R
; PPPPPPPPPP               OOOOOOOOO     LLLLLLLLLLLLLLLLLLLLLLLLYYYYYYYYYYYYY    BBBBBBBBBBBBBBBBBAAAAAAA                   AAAAAAARRRRRRRR     RRRRRRR
;
;
;

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[section/default_value]
width = 100%:-24pt
height = 32pt
offset-x = 12pt
offset-y = 0.5%
padding-left = 1pt
padding-right = 0

line-size = 3pt

background = ${colors.transparent}
foreground = ${colors.foreground}

wm-restack = bspwm
override-redirect = false

modules-left = round-left bspwm round-right
modules-center = round-left xwindow round-right
modules-right = round-left pulseaudio separator memory separator cpu separator eth separator bluetooth separator date separator powermenu round-right

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=13;3
font-1 = JetBrainsMono Nerd Font:pixelsize=25;5
font-2 = Material Design Icons Desktop:style=Bold:pixelsize=32;3
font-3 = JetBrainsMono Nerd Font:pixelsize=20;3

[bar/main_top]
inherit = section/default_value
name = main_bar
monitor = DP-0

[bar/secondary_top]
inherit = section/default_value
name = secondary_bar
monitor = HDMI-1

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
