;
;
; MMMMMMMM               MMMMMMMM     OOOOOOOOO     DDDDDDDDDDDDD       UUUUUUUU     UUUUUUUULLLLLLLLLLL             EEEEEEEEEEEEEEEEEEEEEE   SSSSSSSSSSSSSSS 
; M:::::::M             M:::::::M   OO:::::::::OO   D::::::::::::DDD    U::::::U     U::::::UL:::::::::L             E::::::::::::::::::::E SS:::::::::::::::S
; M::::::::M           M::::::::M OO:::::::::::::OO D:::::::::::::::DD  U::::::U     U::::::UL:::::::::L             E::::::::::::::::::::ES:::::SSSSSS::::::S
; M:::::::::M         M:::::::::MO:::::::OOO:::::::ODDD:::::DDDDD:::::D UU:::::U     U:::::UULL:::::::LL             EE::::::EEEEEEEEE::::ES:::::S     SSSSSSS
; M::::::::::M       M::::::::::MO::::::O   O::::::O  D:::::D    D:::::D U:::::U     U:::::U   L:::::L                 E:::::E       EEEEEES:::::S            
; M:::::::::::M     M:::::::::::MO:::::O     O:::::O  D:::::D     D:::::DU:::::D     D:::::U   L:::::L                 E:::::E             S:::::S            
; M:::::::M::::M   M::::M:::::::MO:::::O     O:::::O  D:::::D     D:::::DU:::::D     D:::::U   L:::::L                 E::::::EEEEEEEEEE    S::::SSSS         
; M::::::M M::::M M::::M M::::::MO:::::O     O:::::O  D:::::D     D:::::DU:::::D     D:::::U   L:::::L                 E:::::::::::::::E     SS::::::SSSSS    
; M::::::M  M::::M::::M  M::::::MO:::::O     O:::::O  D:::::D     D:::::DU:::::D     D:::::U   L:::::L                 E:::::::::::::::E       SSS::::::::SS  
; M::::::M   M:::::::M   M::::::MO:::::O     O:::::O  D:::::D     D:::::DU:::::D     D:::::U   L:::::L                 E::::::EEEEEEEEEE          SSSSSS::::S 
; M::::::M    M:::::M    M::::::MO:::::O     O:::::O  D:::::D     D:::::DU:::::D     D:::::U   L:::::L                 E:::::E                         S:::::S
; M::::::M     MMMMM     M::::::MO::::::O   O::::::O  D:::::D    D:::::D U::::::U   U::::::U   L:::::L         LLLLLL  E:::::E       EEEEEE            S:::::S
; M::::::M               M::::::MO:::::::OOO:::::::ODDD:::::DDDDD:::::D  U:::::::UUU:::::::U LL:::::::LLLLLLLLL:::::LEE::::::EEEEEEEE:::::ESSSSSSS     S:::::S
; M::::::M               M::::::M OO:::::::::::::OO D:::::::::::::::DD    UU:::::::::::::UU  L::::::::::::::::::::::LE::::::::::::::::::::ES::::::SSSSSS:::::S
; M::::::M               M::::::M   OO:::::::::OO   D::::::::::::DDD        UU:::::::::UU    L::::::::::::::::::::::LE::::::::::::::::::::ES:::::::::::::::SS 
; MMMMMMMM               MMMMMMMM     OOOOOOOOO     DDDDDDDDDDDDD             UUUUUUUUU      LLLLLLLLLLLLLLLLLLLLLLLLEEEEEEEEEEEEEEEEEEEEEE SSSSSSSSSSSSSSS   
;
;
                                                                                                                                                            
[module/round-left]
type = custom/text
content = %{T2}%{T-}
content-foreground = ${colors.background}

[module/round-right]
type = custom/text
content = %{T2}%{T-}
content-foreground = ${colors.background}

[module/separator]
type = custom/text
content = %{T2}█%{T-}
content-foreground = ${colors.background}

[module/systray]
type = internal/tray

format-margin = 8
tray-spacing = 16

[module/bspwm]
type = internal/bspwm

pin-workspaces = true

format-background = ${colors.background}
format-radius = 12

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline = ${colors.primary}
label-active-padding = 1


label-occupied = %name%
label-occupied-background = ${colors.background}
label-occupied-foreground = ${colors.primary}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-background = ${colors.background}
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
format-background = ${colors.background}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${colors.background}

label-volume = %percentage%%
ramp-volume-foreground = ${colors.primary}
ramp-volume-0 =%{T4}󰕿%{T-}
ramp-volume-1 = %{T4}󰖀%{T-}

format-muted = <label-muted>
label-muted = %{T4}󰝟%{T-} muted
label-muted-foreground = ${colors.disabled}
label-muted-background = ${colors.background}

click-right = pavucontrol

[module/memory]
type = internal/memory
interval = 2
format-background = ${colors.background}
format-prefix = %{T4} %{T-}
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-background = ${colors.background}
format-prefix = %{T4}󰍛 %{T-}
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-background = ${colors.background}
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected-background = ${colors.background}
label-connected-foreground = ${colors.primary}
label-connected = %{T4}󰈀 %{T-}

[module/date]
type = internal/date
interval = 1
format-background = ${colors.background}
format-prefix = %{T4} %{T-}
format-prefix-foreground = ${colors.primary}

date = %d/%m/%Y %H:%M

label = %date%
label-foreground = ${colors.foreground}

[module/powermenu]
type = custom/text 
content =" " 
content-padding = 1
click-left = $HOME/.config/rofi/powermenu/type-1/powermenu.sh &
content-foreground =  ${colors.alert}
content-background = ${colors.background}

[module/bluetooth]
type = custom/script

exec = $HOME/.config/polybar/scripts/bluetooth.sh
interval = 5
format-background = ${colors.background}
format-foreground = ${colors.foreground}

format-prefix = %{T4}󰂯 %{T-}
format-prefix-foreground = ${colors.primary}

label = %output%

